# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 10:19
from __future__ import unicode_literals

import article.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.FileField(default=b'', upload_to=article.models.get_upload_file_name),
        ),
    ]
